version: '3.8'
services:
  wx-web-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 1002
        HOST_GID: 1002
    container_name: wx-web-backend
    working_dir: /app
    command: python -u wx-web-backend/app/mqtt_to_db.py
    environment:
      - SQLITE_PATH=/data/weather.db
    volumes:
      - ./data:/data:rw
      - ./wx-web-backend.secrets:/run/secrets/wx-web-backend.secrets:ro
    secrets:
      - wx-web-backend-secrets
    restart: unless-stopped
    networks:
      - wx-web-network
  wx-web-graph-generator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 1002
        HOST_GID: 1002
    container_name: wx-web-graph-generator
    working_dir: /app
    command: python -u wx-web-graph-generator/graph_generator.py
    environment:
      - SQLITE_PATH=/data/weather.db
      - STATIC_DIR=/data/static
    volumes:
      - ./data:/data:rw
    restart: unless-stopped
    networks:
      - wx-web-network
  wx-web-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 1002
        HOST_GID: 1002
    container_name: wx-web-frontend
    working_dir: /app
    command: python -u wx-web-frontend/app.py
    environment:
      - SQLITE_PATH=/data/weather.db
    volumes:
      - ./data:/data:rw
      - ./wx-web-frontend.secrets:/run/secrets/wx-web-frontend.secrets:ro
    secrets:
      - wx-web-frontend-secrets
    restart: unless-stopped
    networks:
      - wx-web-network
  wx-web-explorer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 1002
        HOST_GID: 1002
    container_name: wx-web-explorer
    working_dir: /app
    command: python -u wx-web-explorer/app.py
    environment:
      - SQLITE_PATH=/data/weather.db
    volumes:
      - ./data:/data:rw
    restart: unless-stopped
    networks:
      - wx-web-network
  wx-web-alerter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 1002
        HOST_GID: 1002
    container_name: wx-web-alerter
    working_dir: /app
    command: python -u wx-web-alerter/app.py
    environment:
      - SQLITE_PATH=/data/weather.db
    volumes:
      - ./data:/data:rw
      - ./wx-web-alerter.secrets:/run/secrets/wx-web-alerter.secrets:ro
    secrets:
      - wx-web-alerter-secrets
    restart: unless-stopped
    networks:
      - wx-web-network
  wx-web-nginx:
    build:
      context: ./wx-web-nginx
      dockerfile: nginx.Dockerfile
    container_name: wx-web-nginx
    ports:
      - "8099:8080"
    depends_on:
      - wx-web-frontend
      - wx-web-explorer
      - wx-web-alerter
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./webstats:/webstats
    networks:
      - wx-web-network
  wx-web-goaccess:
    build:
      context: .
      dockerfile: goaccess.Dockerfile
    container_name: wx-web-goaccess
    volumes:
      - ./logs/nginx:/logs
      - ./webstats:/webstats
      - ./goaccess.conf:/etc/goaccess/goaccess.conf:ro
    depends_on:
      - wx-web-nginx
    networks:
      - wx-web-network

secrets:
  wx-web-backend-secrets:
    file: wx-web-backend.secrets
  wx-web-alerter-secrets:
    file: wx-web-alerter.secrets
  wx-web-frontend-secrets:
    file: wx-web-frontend.secrets

networks:
  wx-web-network:
    driver: bridge